---
title: "EsH"
author: "Jia"
output: 
  html_document: 
    df_print: default
editor_options: 
  chunk_output_type: console
---

# 摘要

血蓝蛋白(Hemocyanin,Hc)广泛存在于节肢动物和软体动物的血淋巴中，主要行使氧气运输功能，同时也行使着免疫、存储等功能，是一种重要的功能蛋白。中华绒螯蟹(*Eriocheir sinensis*,Es)俗称河蟹、大闸蟹，是一种重要的经济水产，属于节肢动物门。节肢动物的血蓝蛋白与软体动物血蓝蛋白在基因和形态上都完全不同，现有的研究对于软体动物血蓝蛋白的研究较多，对于节肢动物血蓝蛋白的研究较少。
本研究借助冷冻电镜三维重构技术(Cryo-electron microscopy 3D-reconstruction)，获得了中华绒螯蟹血蓝蛋白的？？A分辨率三维结构，并构建了原子模型。以获得的模型为基础，分析了亚基之间的相互作用，氧气运输过程中的变构协同效应。

# 前言

## 1.1 血蓝蛋白的生理功能
### 氧气运输
血蓝蛋白广泛存在于节肢动物和软体动物的血淋巴中，行使运输氧气的生理功能。当血蓝蛋白位于腮等氧气分压高的器官时，活性部位的两个Cu以Cu2+的形式存在，结合一个O2形成蓝色的氧合血蓝蛋白(oxyhemocyanin);当血蓝蛋白运输氧到氧分压低的器官或组织时，Cu以Cu+的形式存在，O2从活性部位释放，形成无色的脱氧血蓝蛋白(hemocyanin)[1]。

血蓝蛋白与蚯蚓血红蛋白、血红蛋白并称为动物界中的3种呼吸蛋白[2-5]。这3种呼吸蛋白是同功非同源关系，其中，蚯蚓血红蛋白是最古老最原始的呼吸蛋白，实现了从依靠气体渗透作用的被动式摄取氧，到呼吸蛋白运载氧的飞跃。蚯蚓血红蛋白不稳定，易氧化，后来出现的节肢动物以较稳定的血蓝蛋白代替了蚯蚓血红蛋白。但是血蓝蛋白与氧的结合能力很弱，因此在部分高等无脊椎动物和脊椎动物中，更髙效的血红蛋白替代了血蓝蛋白。血蓝蛋白不仅在呼吸蛋白的分子进化中具有承上启下的重要意义，而且是多数甲壳动物和软体动物（头足类和腹足类）的呼吸蛋白，在动物界中的分布范围仅次于血红蛋白，具有重要的研究价值。

### 免疫功能
甲壳动物的血蓝蛋白不仅具有氧气运输功能，还具有酚氧化物酶活性、抗菌肽活性、凝集活性等免疫功能[2-8]，是一种重要的免疫分子。

血蓝蛋白75Kd亚基与人Ig存在高度同源的同源区域[1-5]，可以与抗人IgG发生交叉反应，说明血蓝蛋白具有发挥免疫功能的结构基础。章跃陵等[1-6]报道，甲壳动物凡纳滨对虾(*Litopenaeus vannamei*)在感染病毒后，肝胰脏中的血蓝蛋白p73、p75亚基浓度明显升高，说明其通过某些途径参与了机体的免疫防御。

甲壳动物血蓝蛋白与酚氧化酶在物理化学性质[1-31]、蛋白序列和三级结构[1-31]、基因序列等[1-32]方面非常相似。在体外条件下，血蓝蛋白受到胰岛素、十二烷基磺酸钠、尿素和生物防御分子、血细胞成分等物质的诱导，以及在轻微水解的条件下，均可表现出类似酚过氧化物酶的活性[1-33,34,35,36]。关于血蓝蛋白和酚氧化酶的进化关系，有两种对立的观点：多数学者认为，血蓝蛋白由酚氧化酶演化而来[1-26,27]，甲壳动物血蓝蛋白的活性来自于进化过程中酚氧化酶功能的残留。少数学者认为，酚氧化酶源于血蓝蛋白[1-32,39,40]。

抗菌肽是动物免疫系统产生的广谱抗菌性小分子多肽。血蓝蛋白也具有抗菌肽的活性。Destoumieux等[1-41]报道甲壳动物细角滨对虾(*Litopenaeus stylirostris*)中分子量7.9Ku和8.3Ku和凡纳滨对虾中分子量2.7Ku的阴离子抗菌肽，都与各自血蓝蛋白C-末端的氨基酸结构有着95%～100%的氨基酸序列相同。Zhang等[1-30]与Decker等[1-37]也报道了，血蓝蛋白源的抗菌肽在被释放前就已经具有了部分抗菌功能，即血蓝蛋白本身就具有抗菌功能。

血蓝蛋白的凝集作用能使细菌、脊椎动物红细胞等发生凝集，从而使其失去感染能力，也促进了血细胞对外来物的识别和吞噬。章跃陵等[1-47,48]报道凡纳滨对虾血蓝蛋白对鱼、鸡、鼠、人的红细胞有明显的凝集活性，对副溶血弧菌、溶藻酸弧菌等6种虾类致病病毒具有凝集活性。血蓝蛋白的凝集活性也同一般的凝集素一样，会被α-半乳糖、α-D葡萄糖、甘露醇和N-乙酰神经氨基酸等4种糖显著抑制。Tsing等[1-49]和Sequeira等[1-50]报道，印吉单肢虾(*Sicyonia ingentis*)和日本囊对虾(*Penaeus japonicus*)在受到致病菌威胁，体内凝集作用增强时，血蓝蛋白的含量同时升高。

### 其他功能

血蓝蛋白还具有物质储存、维持渗透压等功能[2-6，7]。血蓝蛋白占血淋巴蛋白的90%以上[1-1]，由于总含量巨大，天然就是一个优良的蛋白质储存仓库。在饥饿状态下，血蓝蛋白可以为甲壳动物的其他关键蛋白合成提供原料，维持基本的生理功能。血蓝蛋白在血浆蛋白中占比极高，血蓝蛋白产生的胶体渗透压，很大程度上决定了血淋巴的胶体渗透压。甲壳动物通过调节血蓝蛋白的总含量和形成低聚物的程度调节血淋巴渗透压，对于适不同渗透压的水环境具有重要意义。

## 1.2 现有结构研究

节肢动物的血蓝蛋白与软体动物血蓝蛋白生理功能几乎相同，但在基因结构和形态上都完全不同。一般认为两者由不同的oxygen-consuming enzyme进化而来，在进化上没有联系(burmester,2001)。根据血蓝蛋白结构上的差异以及来源动物的生物学分类不同，可以按照下表进行分类。

* 节肢动物门 Arthropoda
* 软体动物门 Mollusca
  * 头足纲 Cephalopoda
  * 腹足纲 Gastropoda

### 软体动物血蓝蛋白结构

软体动物血蓝蛋白由六聚体的Building Blocks组成紧凑的球状或柱状结构，分为两大亚类(subclasses)：头足纲血蓝蛋白为十聚体柱状结构，具有D5对称性。腹足纲血蓝蛋白也为十聚体，但是不存在上下的对称性，具有首端和尾端的分别。

软体动物血蓝蛋白的亚基(subunit)长\~400kDa，每个亚基折叠为7\~8个称为functional unit (FU)的球状结构（头足纲7个，腹足纲8个），每个FU的分子量约为45~65kDa，均带有一个双铜离子的氧结合活性中心。每个FU之间虽然氨基酸序列上存在不同，但是高度保守，有着约60%~70%的序列同源性。这种同源性不仅存在于同一亚基的不同FU之间，在不同物种的FU之间也存在着同样程度的序列相似性。

### 节肢动物血蓝蛋白结构

节肢动物的血蓝蛋白是由6个高度螺旋、分子量70\~80kDa的亚基构成的六聚体[1-6]，亚基的种类有3\~8种。每个亚基可以按照空间上的聚集，分为3个结构域。N端为第一结构域，C端为第三结构域，第二结构域位于中间，含有血蓝蛋白的活性部位，活性部位由三个组氨酸和与其咪唑氮原子配位结合的2个铜离子组成。在六聚体中，一三结构域包裹着第二结构域，位于外侧，第二结构域位于六聚体内部，只有O2等小分子物质可以接近。[1-7]。

六聚体之间也具有相互作用力，可以形成六聚体低聚物。甲壳动物的六聚体独立存在或形成2x6聚体低聚物[1-8]，而某些物种的血蓝蛋白六聚体除独立存在外，还会形成更大的2x6、4x6、6x6、8x6聚体，同一物种一般只有一种六聚体低聚物组合形式。六聚体低聚物在总血蓝蛋白中比例也与环境温度和pH有关，低温与高pH的情况下，六聚体低聚物的含量会上升[1-9]。



## 1.3 研究目的

如前所述，血蓝蛋白主要承担着运输氧气的功能。生物大分子的功能与其结构密切相关。解释血蓝蛋白在氧气运输过程中，各个亚基之间的协同效应，活性位点结合释放氧时的构象变化，都需要高分辨率的血蓝蛋白结构作为基础。

解析血蓝蛋白的结构，对于理解血蓝蛋白的免疫功能也有重要意义。在免疫学上，血蓝蛋白可以与多糖结合，或人工耦合小分子后发挥作用。血蓝蛋白本身稳定的四级结构和亚基为多糖或小分子一个高度有序的骨架。了解这个骨架的结构为免疫学上进一步设计改造血蓝蛋白提供了结构基础，可以更有针对性地寻找位于表面的耦合结合位点，避开由于空间位阻无法结合到的位点。

血蓝蛋白属于一大类拥有同源性的蛋白家族。得到血蓝蛋白的高分辨结构，与同家族的蛋白进行比较，是理解特定蛋白序列与蛋白折叠三维结构之间关系的重要方法。

血蓝蛋白在电镜下易于辨认，作为标记物也可以用于观察特异分子的分布。


# 材料与方法
## 2.1 中华绒螯蟹血蓝蛋白的提纯
### 采集蟹血淋巴
用清水冲洗新鲜购买的中华绒螯蟹（俗称大闸蟹、河蟹）外壳，使用刷子清理蟹外表泥污，重点清理任意一侧的最后一足，洗净后自然晾干。准备一支装有15ml磷酸盐缓冲液(PBS)的50ml离心管备用。一手带厚手套抓持蟹，另一手使用老虎钳，从根处扭下任意一侧的最后一足，断肢处立即有大量血淋巴流出，迅速用装有15ml磷酸盐缓冲液的50ml离心管接取。待血淋巴不再自行流出，可继续用力捏蟹腹部，挤压出更多血淋巴。接取过程中，应不断震荡离心管使，防止血淋巴因凝血作用而凝固。当操作者用尽力气也无法挤出更多血淋巴流出时，停止收集，盖上离心管，大力震荡3min，产生大量气泡，静置片刻，待气泡混合杂质浮至液体表面，用滴管小心避开上层气泡杂质，吸取收集下层澄清的液体。

### 提纯浓缩
将上步得到的蟹血用高速离心机4℃10,000g离心10min，取上清。再4℃15,000g离心1h，取上清。
使用CsCl梯度离心进一步纯化：用PBS配制45%、35%、25%、15%(w/v)的CsCl溶液各3ml。按照浓度从高到低，从底部到顶部依次小心加入用于超速离心的内管。将高速离心得到的上清液(0.5~1ml)加到梯度顶层。由于CsCl溶液密度很大，对位的离心管无法用水配平，可使用约65%的蔗糖溶液配平。配平后将内管装入吊桶，使用Hitachi CP100NX超速离心机4℃，35,000rpm离心20h（P40ST转子）。

离心结束后，可以看到离心管内35%到45%的CsCl交界处，有明显的蓝色条带。
使用注射器小心地吸出条带，加入10mlPBS充分混匀，分多次加入100KDa的超滤柱，4℃4000rpm离心浓缩到1ml，
再加满PBS充分吹打混匀，清洗CsCl，浓缩到1ml，再重复清洗2次后，取5μl样品备用，取样后继续浓缩到100μl，用小枪头小心吸出，即得到了纯化浓缩的中华绒螯蟹血蓝蛋白。

## 2.2 样品纯度浓度检查
使用5%的SDS-PAGE电泳上步取得的5μl样品，检查EsH样品的分子量大小和纯度（针对蛋白杂质）。

取最终浓缩样品3μl进行负染色，使用电子显微镜观察，检查EsH的完整程度、聚集状态和纯度（针对非蛋白杂质）。根据负染色检查的纯度，稀释或进一步使用超滤柱浓缩EsH样品，直到蛋白颗粒可以铺满整个铜网，又不互相重叠。

### SDS-PAGE电泳
将玻璃板固定在制胶架上，按下表配方配置5ml的10%分离胶加入玻璃板之间，加到距离顶约部3cm处，加入无水乙醇压平胶面。约30min后分离胶凝固，清理干净无水乙醇，加入按下表配制的浓缩胶，插好梳子避免气泡。待30min后浓缩胶凝固，取出玻璃板装上支架，放入电泳槽，加入TBE电泳缓冲液，在液面下拔出梳子。

样品与1μl LoadingBuffer混合，加入胶孔。在一孔加入1μl marker。盖上盖子，连接电源，注意正负极。开始时以80V电压电泳30min，使得样品在浓缩胶中充分浓缩，随后调节电压到150V，电泳40min。

电泳结束后，打开电泳槽，取出凝胶，用考马斯亮蓝染液浸泡凝胶，摇床上摇动染色30min，倒出染液，用清水冲洗净凝胶。用脱色液浸泡，摇床上摇动1h脱色。拍照记录。

成分 | 浓缩胶 | 10%分离胶
---|---|---
H~2~O|0.68|1.9
30%丙烯|0.17|1.7
1MTris-HCl|0.13|-
1.5MTris-HCl|-|1.3
10%SDS|0.01|0.05
10%AP|0.01|0.05
TEMED|0.01|0.02
total|1ml|5ml

### 电镜负染色检查
取铺有连续碳支持膜的400目铜网，使用PELCO easiGlow辉光放电仪进行亲水处理。将样品滴加在亲水处理后的铜网上，吸附1min，用滤纸吸去液体，但不要完全吸干。随后立即滴加3μl的1%甲酸铀染料，立刻用滤纸吸去甲酸铀但不要吸干，重复滴加吸干操作一次，再滴加3μl1%甲酸铀，染色15s，用滤纸吸去多余的甲酸铀，但不要完全吸干，在空气中干燥45s左右，此时铜网表面才应当完全干燥。
将制备好的铜网装上样品杆，使用JEM100CX-II电镜观察。首先在LowMag模式下，检查铜网负染情况，是否有污染和碳膜破损。找到一块覆有完整碳膜且没有大块污染的网孔，加入小号物镜光栏提高图像衬度，在Mag模式20万倍放大倍数下观察：蛋白颗粒是否完整，蛋白颗粒是否粘连，是否混有其他蛋白，背景中是否有杂质。

### 甲酸铀染液的制备
甲酸铀(Uranium Formate,UF)相比醋酸铀(Uranium Acetate,UA)，碳链碳数更少，染色的背景更为干净，更细腻。在此提供一种由UA制备UF的方法。

取500μl 2%UA到一EP管中，逐滴加入1M NaOH，产生白色固体，10000g10min离心使沉淀聚集在管底，继续向上清中滴加1M NaOH，直到没有新的沉淀产生，此时溶液颜色应当由黄色变为无色，pH应当大于14，大约需要200μl 1M NaOH。吸去上清液，向沉淀中加入300μl水，涡旋震荡以充分清洗沉淀，再10000g10min离心使沉淀聚集在管底，测量上清pH后吸去上清丢弃。根据pH变化适度改变加水多少，重复清洗沉淀，直到上清pH达到8\~9。pH过高会有NaOH残留，过低会损失铀。随后加入100μl水，1μl一次，缓慢滴加 4M甲酸(80%甲酸约16M，混3倍体积水制成)至沉淀完全溶解，此时pH应当为5，大约需要6μl 4M甲酸。加水至总体积1ml，即得到1% UF。

## 2.3 冷冻电镜制样与观察
### 冷冻制样
冷冻制样在本实验室进行。使用PELCO easiGlow辉光放电仪亲水处理覆有1.2-1.3规格有孔碳支持膜的铜网上（Quantifoil公司）。使用Vitrobot专用镊子夹住铜网，放入Vitrobot，将4μl样品滴到铜网表面，使用？？滤纸，在BlotForce=？，BlotTime=2s的条件下吸去多余液体，使样品在微筛网上形成一层薄膜，随后快速投入液氮冷却的液态乙烷中，使样品中的水形成玻璃态冰，固定住样品。

### 低分辨数据的收集
较低分辨的数据在广东省疾病预防控制中心收集，用于制样条件摸索和模型质量验证。使用Gatan626冷冻传输架将冷冻好的铜网转移到预冷好的冷冻样品杆上，使用FEI公司的Tecnai G2 F20观察拍摄。拍摄条件：Low Dose模式，200Kv加速电压，100k放大倍数，35e/A^2^，Apixel=1.07，欠焦量在2μm\~3.5μm，FEI Eagel相机收集4k×4K照片。

### 高分辨数据的收集
高分辨数据在浙江大学冷冻电镜中心收集。使用配备Gatan Summit K2直接电子探测相机的FEI Titan Krios冷冻电镜拍摄。电镜工作在300Kv加速电压下，放大倍数29,000倍，此放倍数下Apixel=1.014，Low Dose模式下，调节光斑大小使得电子剂量率为6e/s/A^2^。SerialEM软件用于辅助收集，设置欠焦量范围1μm\~3μm，因对拍摄位置定位精度要求不高，使用快速收集脚本自动拍照。直接电子探测相机工作在SuperResolution模式下，过采样后得到Apixel=0.507，以Movies的形式收集数据，每套数据24帧，总曝光时间为6s。

## 2.4 三维重构

三维重构即将二维的电镜照片，通过一系列数据变换，恢复其三维信息。数据处理和三维重构过程主要使用目前主流的软件包EMAN2和Relion2.1，一些特定处理使用该方向上的专用软件，如用于漂移矫正的MotionCorr2;用于自动框选颗粒的Gautomatch;进行CTF(Contrast Transfer Founction)参数估计的Gctf。一些自行编写的脚本也用于数据组织和分析。

### 低分辨数据的重构
在广东省疾控中心拍摄的低分辨数据在实验室工作站处理。使用EMAN2的e2boxer模块半自动框选颗粒。先在swam模式下，点击选择10个左右的模板，模板应尽量选择清晰、独立的颗粒，应尽量包含所有出现的投影模式、欠焦量、冰厚度、冰污染程度、颗粒衬度。调整threshold使得尽可能多的颗粒被自动框选，完成后保存颗粒坐标。使用Relion的Particle Extraction功能，将颗粒坐标导入，进行reference free 2D分类。选取清晰完整的分类（尽量包含各个取向的投影），使用EMAN2的initial model功能构建初始模型。再使用Relion对初始模型使用经过CTF校正的颗粒进行精修，得到低分辨模型。

### 高分辨数据的重构
在浙江大学冷冻电镜中心收集的高分辨数据数据量庞大，在实验室工作站和东校区实验中心服务器上进行计算。首先使用MotionCorr2软件处理原始的Movies，校正图像漂移，进行Dose Weighting即去除被电子损伤较为严重的帧。使用Gctf软件进行CTF参数估计，同时进行EPA(Equal Phase Analysis)，估算图片的最终分辨率。使用自行编写的脚本和人工目测检查，筛查去除最终分辨率低、有大面积冰污染、拍在碳膜上的照片。

使用Gautomatch软件，以20A低通滤波后的低分辨模型在各个空间方向上的投影为模板，自动框选颗粒。手动调整选到颗粒的cutoff threshold，留下尽可能多的颗粒和尽可能少的杂质。使用Relion的Particle Extraction功能，将颗粒bin2（一种压缩方法，将相邻2个像素相加）以加速计算。此后的步骤都在Relion中进行。进行无参考（reference free）2D分类，保留清晰、完整、颗粒数多的分类，去除冰晶、污染产生的不清晰分类，去除破碎损伤的蛋白产生的不完整分类。重复进行无参考2D分类，直到冰晶、污染颗粒都被去除。使用Relion以低分辨模型为参考，进行3D分类，选取与低分模型整体结构相似的分类。使用自行编写的脚本检查这一分类中的颗粒质量。

使用Gctf软件对3D分类中选出的最好分类中的每一个颗粒进行Local CTF参数估计，重新导入不压缩的颗粒，使用自行编写的脚本替换原有的Global CTF值。使用这些颗粒精修低分辨模型，得到较高分辨率的的电子密度模型。将同一批颗粒转为EMAN格式并写入CTF参数，使用jspr软件进行更为精密的Refine，最终获得了？？A分辨率的电子密度模型。

使用Relion计算结构因子，sharpen模型，构建并使用solvent msak，以FSC=0.14的标准计算最终分辨率。


## 2.5 构建原子模型

EsHc的序列来自Sun等[Molecular cloning, characterization and mRNA expression ofcopper-binding protein hemocyanin subunit in Chinese mitten crab,Eriocheir sinensis]，GenBank: JF802122.1。以同为甲壳亚门(Crustacean)的加州刺龙虾(Panulirus interruptus)血蓝蛋白结构(PDB:1HC1)作为参考，使用蛋白质同源建模工具ModBase(https://modbase.compbio.ucsf.edu/modbase-cgi/)建立EsH的伪原子模型。建模完成后与已发表的1HC1结构进行目测比对以确保正确。
使用Chimera软件，打开电子密度(map)和理论计算建立的EsH伪原子模型(model)，手动调整map与model的位置，使得model大体对应到map上的对应位置，再使用Fit in map功能将model精细匹配到map上的对应位置。保存model和map的相对位置。使用Coot软件打开经过粗略对准的map和model进行进一步精修。调整model中的氨基酸碳主链，修改伪原子模型中的预测错误，使其碳链大体走向符合map密度的走向，同时也符合氨基酸折叠基本规律。调整model中的氨基酸侧链位置使其符合map中的侧链密度，同时也符合侧链键长键角基本规律。使用Phenix软件的real space refine功能精修侧链位置。再使用Coot手动调整异常位置，如异常的碳主链平面角，过近(小于2.2A)的原子距离等等。最终模型使用PDB的validation功能打分。

# 结果与讨论

## EsH的提纯与鉴定
15%~45%(w/v)CsCl密度梯度离心后的离心管如图1A，可以在35%和45%浓度两层CsCl之间看到蓝色条带。样品的SDS-PAGE电泳结果如图1B。EsH分子量理论大小为432kD，在电泳图中相应分子量处可以看到一条非常浓的条带。且在72kD处可以看到分离了的亚基条带，也与理论相符。电泳结果非常纯净，没有杂带，表明蛋白纯度很高，没有其他杂蛋白，说明高速离心配合密度梯度离心的方法有效纯化了节肢动物的血蓝蛋白。

首次负染检查发现样品的浓度过高，蛋白颗粒多层重叠，铺满了整个铜网，需要稀释。经过多次摸索稀释条件，最终发现稀释到最初浓度的1/9，达到？？最为合适。负染照片如图1D，EsH的浓度合适，密布整个铜网表面，基本没有杂质，达到了继续进行冷冻电镜数据收集的标准。相比起没有经过纯化的样品负染照片（图1C），纯化后的样品质量大幅提升。理论上讲，EsH应为近似圆柱体结构，有圆形的顶部投影(top view)和矩形的侧方投影(side view)。从照片中可以看到这些top view（图1DE红框）和side view（图1DE蓝框），说明蛋白的结构完整，没有因为分离提纯过程产生分解、形变。

## EsH的序列分析

利用BLAST与相近物种比对。

## 数据处理各阶段结果

总共获得的2291套Movies经过漂移矫正之后目视检查，去除拍在碳膜上的照片，剩下1850张可用照片。图？？？展示了一张经过漂移校正的冷冻电镜原始照片，图？？？展示了一张没有经过漂移校正的冷冻电镜照片，漂移校正的效果很显著。

EPA分析后，得到每张照片的预计分辨率，使用脚本（附件1.1）以每0.1A为一组，作分辨率的分布图（图？？？），可以看到照片的分辨率集中在3.4A左右。说明大部分照片的分辨率较为理想，有很大可能获得一个很好的最终分辨率。
使用Gautomatch自动框选得到346,279个颗粒，这些颗粒经过连续三轮的reference free 2D分类，筛选至202483个，图？？展示了这些颗粒的2D classAverage。再进行3D分类，产生了4组颗粒，图？？展示了各组的三维结构，各组的颗粒数分别为64798，6062，32432，99191个。保留颗粒数量最多、三维结构最为细腻的一个分类（图？？箭头标出），即99191个高质量颗粒被保留。
一系列2D和3D分类筛选去除了很多低质量的颗粒，使用脚本（附件1.2）查找低质量颗粒的来源，找出全是低质量颗粒的照片，以每0.1A为一组，作分辨率的分布图（图？？？），可以看出低质量颗粒的来源大部分都是低质量的照片，与理论预期相符。

计算高质量颗粒计算的Local CTF参数，使用脚本替换原有的Global CTF参数。使用Relion进行三维重构的模型得到了得到3.47A分辨率的电子密度模型。

最终分辨率。

## EsH三维重构结果
### 整体结构
利用冷冻电镜单颗粒技术，获得的EsH三维结构，图？？展示了模型的顶部视图（top view），将模型沿水平x轴旋转90度，得到图？？展示的侧方视图（side view）。
电子密度图显示，EsH整体为圆柱体结构，直径约？？A，高约？？A。EsH整体由6个亚基组成，亚基呈D3对称性排列，即上下两层每层含有3个亚基，这3个亚基以圆柱的轴为对称轴成旋转对称，同时每个亚基以圆柱轴中点为对称点，与对侧的亚基成中心对称。
EsH电子密度模型的整体分辨率为？？？A。局部分辨率如图？？。可以看到靠近中心的部分分辨率相对较高（红色），因为蛋白靠近中心处一般较为稳定，柔性片段较少；靠近外侧的一些肽链柔性强，位置不确定性高，得到的分编率也相对稍低（蓝色）。在电子密度模型中的大部分区域，可以清晰地分辨出α-helix和β-sheet等蛋白质二级结构，在较为稳定的部分，甚至可以分辨出氨基酸的侧链（图？？？），说明FSC方法计算的分辨率与模型质量相符，没有出现overfitting。


### 原子模型与亚基结构

使用2.5节中方法获得了EsH亚基的结构模型，这个模型可以很好地匹配电子密度模型（图？？？）。（图？？？）比较了理论预测得到的模型与经过调整的最终模型，红色圈表示了调整较大的部分，主要是一些柔性的loop。（图？？？）比较了本研究获得的模型与通过X射线晶体学解析的加州刺龙虾和美洲鲎(Limulus polyphemus)血蓝蛋白模型，在2处靠近外侧的loop结构上，本研究都解出了另外两个结构无法解析的接结构。

EsH的亚基在结构上可以分为三个部分：N端结构域(Hemocyanin_N)从N端开始，至第？？位氨基酸残基(AA)，亚基组装后，位于EsH整体的外侧（图？？？），这一部分的肽链形成了大量α-helix二级结构，α-helix再形成桶状三级结构，虽然位于蛋白外侧，但也很稳定，从局部分辨率图（图？？）中可以看出，这一部分达到了相对较高的局部分辨率；中间结构域(Hemocyanin_M)从？？位至？？位AA，亚基组装后，位于EsH整体的内侧（图？？？），这一部分的肽链形成了大段α-helix，小段β-sheet的二级结构，α-helix形成桶状三级结构，加之位于蛋白内侧，疏水作用的额外稳定效果，结构非常稳定，从局部分辨率图（图？？）中可以看出这一部分的局部分辨率也是较高的。C端结构域(Hemocyanin_C)从第？位AA开始，至C端，亚基组装后，位于EsH整体的外侧（图？？？），这一部分肽链的形成了一些分散的β-sheet和α-helix，被较长的loop连接，柔性较强，从局部分辨率图（图？？）中可以看出，这一部分的局部分辨率相对较差，且存在一些柔性过大，无法解得电子密度的片段（图？）。

血蓝蛋白的活性中心位于中间结构域，靠近EsH整体的内侧。第228、232、259位和379、383、419位的组氨酸(His)，相近的三个His络合一个铜离子形成活性中心（图？？）。活性中心较为保守稳定，可以解析到清晰的His侧链和铜离子密度。

### 亚基之间的相互作用

相邻亚基之间存在氢键连接，氢键位置如图（图？？）。

疏水作用

静电力

## 协同效应结构基础？


# 参考文献

# 缩略词

CTF Contrast Transfer Founction  衬度传递函数
Es  Eriocheir sinensis  中华绒螯蟹
EPA  Equal Phase Analysis  等相位分析
FSC  Fourier shell correlation  傅立叶壳相关系数
Hc  Hemocyanin  血蓝蛋白
PBS  Phosphate Buffer Saline  磷酸盐缓冲溶液
UA  Uranium Acetate  醋酸铀
UF  Uranium Formate  甲酸铀
PAGE  Polyacrylamide Gel Electrophoresis  聚丙烯酰氨凝胶电泳
SDS  Sodium Dodecyl Sulfate  十二烷基磺酸钠
h  hour  时
min  minute  分
s  second  秒

# 附录

脚本

最终fsc

序列
